version = 1

test_patterns = ["tests/test_*.py"]

exclude_patterns = ["migrations/**"]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
  "tests/requirements.txt",
  "doc/requirements.txt"
]

  [analyzers.meta]
  runtime_version = "3.x.x"
  
