version = 1

test_patterns = ["tests/*.py"]

exclude_patterns = ["migrations/**"]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
  "/requirements.txt",
  "tests/requirements.txt",
  "doc/requirements.txt"
  ]

  [analyzers.meta]
  runtime_version = "3.x.x"
  
